### ISSUE TITLE
color rgba() method is locale dependent

### ISSUE THREAD

**Issue by nRo** [mdewilde/chart#1]
the [Color](https://github.com/mdewilde/chart/blob/master/src/main/java/be/ceau/chart/color/Color.java)#rgba() method produces an invalid string if the system locale uses comma as decimal separators.
example output on a german system: 

> rgba(255,0,0,1,000)

it could simply be changed to
`		return "rgba(" + r + "," + g + "," + b + "," + String.format(Locale.US,"%.3f", a) + ")";
`

**Comment by mdewilde** [comment]
Thank you for the report.
I've added your suggested change to the upcoming 2.0.0 version:
https://github.com/mdewilde/chart/commit/69cd483766a165656651e224a4c768f8fea52791
