### ISSUE TITLE
Add support for attribute "stack" 

### ISSUE THREAD

**Issue by davidclaesson** [mdewilde/chart#14]
I need to use the attribute "stack" in BarDataset. I cant find a way to add it, would be great if you could add this option. For example see: http://www.chartjs.org/samples/latest/charts/bar/stacked-group.html

**Comment by mdewilde** [comment]
This is in fact possible, using property stacked in either XAxis or YAxis.
I've added an example of how you could go about implementing this in a test class: https://github.com/mdewilde/chart/blob/master/src/test/java/be/ceau/chart/tests/StackedBarTest.java
