### ISSUE TITLE
XAxis and YAxis Null JSON Issue

### ISSUE THREAD

**Issue by cstack89** [mdewilde/chart#2]
Can you please add @JsonInclude(Include.NON_EMPTY) to the XAxis and YAxis classes? I noticed while trying to setup the BarChart demo from http://www.chartjs.org/docs/#bar-chart that because only Stacked is set the Javascript will not handle the JSON returned from your class as it has null options.

**Comment by mdewilde** [comment]
Thank you for the report.
I've added the change in commit 98ff98a
The change was also added to new version 2.0.1 which should be available from Maven Central shortly.

**Comment by cstack89** [comment]
Thanks! I will test with 2.0.1 tomorrow and let you know how it goes.

**Comment by cstack89** [comment]
Sorry I got pulled away, but I tested it today and everything works as expected. Thanks for the quick turn around!
