### ISSUE TITLE
Add support for the barThickness and barThickness attributes.

### ISSUE THREAD

**Issue by davidklebanoff** [mdewilde/chart#21]
Add support for the `barThickness` and `maxBarThickness` attributes.

https://www.chartjs.org/docs/latest/charts/bar.html#configuration-options

**Comment by mdewilde** [comment]
Added to release 2.4.0
Will be available from Maven Central shortly.
See https://github.com/mdewilde/chart/blob/08bf396c14d8a35a54c149a1c95474c733c59381/src/test/java/be/ceau/chart/tests/BarTest.java#L89 for an example.
