### ISSUE TITLE
Question - Bar y-Axis Tick Range/Steps

### ISSUE THREAD

**Issue by SBastler** [mdewilde/chart#3]
Hello

I'd like to set the y-ticks like that in Chart.js:

`var chartInstance = new Chart(ctx, {
    type: 'bar',
    data: data,
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    max: 100,
                    min: 0,
                    stepSize: 10
                }
            }]
        }
    }
});`

Im new with Chart.java and not sure how to manage that. Is there something missing?

Thank's Stefan

**Comment by mdewilde** [comment]
Thanks for the report.

There is indeed a mismatch with chart.js at the scale, axes and ticks hierarchies.

I've added changes to enable nesting ticks under xAxis and yAxis elements.

The chart you describe can now be created like so:

````java
BarDataset dataset = new BarDataset()
		.setLabel("TickTest")
		.addData(65)
		.addData(59)
		.addData(80)
		.addData(81)
		.addData(56)
		.addData(55)
		.setBorderWidth(1);

BarData data = BarChart.data()
		.addLabel("January")
		.addLabel("February")
		.addLabel("March")
		.addDataset(dataset);

LinearTicks ticks = new LinearTicks()
		.setMin(0)
		.setMax(100)
		.setStepSize(10);

BarScale barScale = new BarScale()
		.addyAxes(BarScale.yAxis().setTicks(ticks));

BarOptions options = BarChart.options()
		.setScales(barScale);

new BarChart(data, options);
````

These changes are available in the repo, though not yet in Maven. Do let me know if this resolves your issue, or if you have further comments.

Kind regards,
Marceau

**Comment by SBastler** [comment]
That's perfect. Thank you!
Kind regards Stefan
